# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # BetterAuth - Configure repositories to use App entities
    BetterAuth\Symfony\Storage\Doctrine\DoctrineUserRepository:
        arguments:
            $userClass: 'App\Entity\User'

    BetterAuth\Symfony\Storage\Doctrine\DoctrineSessionRepository:
        arguments:
            $sessionClass: 'App\Entity\Session'

    BetterAuth\Symfony\Storage\Doctrine\DoctrineRefreshTokenRepository:
        arguments:
            $refreshTokenClass: 'App\Entity\RefreshToken'

    BetterAuth\Symfony\Storage\Doctrine\DoctrineMagicLinkRepository:
        arguments:
            $tokenClass: 'App\Entity\MagicLinkToken'

    BetterAuth\Symfony\Storage\Doctrine\DoctrineEmailVerificationRepository:
        arguments:
            $tokenClass: 'App\Entity\EmailVerificationToken'

    BetterAuth\Symfony\Storage\Doctrine\DoctrinePasswordResetRepository:
        arguments:
            $tokenClass: 'App\Entity\PasswordResetToken'

    BetterAuth\Symfony\Storage\Doctrine\DoctrineTotpRepository:
        arguments:
            $totpClass: 'App\Entity\TotpData'

    BetterAuth\Core\Interfaces\TokenSignerInterface:
        alias: BetterAuth\Symfony\Service\EventDispatchingTokenService
