nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        expose_headers: ['Link']
        allow_credentials: true
        max_age: 3600
    paths:
        '^/auth':
            allow_origin: ['http://localhost:3000']
            allow_credentials: true
        '^/api':
            allow_origin: ['http://localhost:3000']
            allow_credentials: true
        '^/': null
