nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ["%env(FRONTEND_URL)%"]
        allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
        allow_headers: ["Content-Type", "Authorization", "X-Requested-With"]
        expose_headers: ["Link"]
        allow_credentials: true
        max_age: 3600
    paths:
        "^/auth":
            allow_origin: ["%env(FRONTEND_URL)%"]
            allow_credentials: true
        "^/api":
            allow_origin: ["%env(FRONTEND_URL)%"]
            allow_credentials: true
        "^/": null
